import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h4>Header</h4>
        </header>
        {children}
        <header>
          <h4>Header</h4>
        </header>
      </body>
    </html>
  );
}
